apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: production
stringData:
  MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: SuperPassword
